### ISSUE TITLE
При регистрации нового пользователя не высылается письмо

### ISSUE THREAD

**Issue by gearhand** [noggatur/mturk#1]
Это происходит, если в качестве почты для рассылки использовать info@emotionminer.com. Получилось исправить на локальной машине, заменив `service: gmail` в файле [EmaiService.js](https://github.com/noggatur/mturk/blob/master/api/services/EmailService.js#L4) на:
```javascript
host: 'outlook.office365.com',
port: 587,
secure: false,
```

Игорь Степаненко,
NeuroDataLab

**Comment by noggatur** [comment]
Спасибо! Поправил)
